### PR TITLE
feature(log): Create endpoint to stream log of integration

### PR DESCRIPTION
**Pull request by Croway**
Hello, this is a first iteration implementation, I'm interested in the streaming part too, I was thinking about SSE but I can't find much documentation on quarkus and sse, I think that it is possible (and probably simpler) with a websocket.

### CODE REVIEW

**Comment by Delawen** [comment]
Hi @Croway Thanks for this and welcome!

**Comment by Delawen** [comment]
I agree that a websocket and continuous stream of lines is a better approach, but let's start with this :)

**Comment by Delawen** [comment]
Why can't we use the existing `@WithKubernetesTestServer`? Or maybe spin up a Kind with camel-k cluster on the github job.

**Comment by Croway** [comment]
I didn't know about kind! seems interesting, I'll try it out. Thanks

**Pull request merged**
