### PR TITLE
feature: Wait for the warmup instead of throwing exception

### PR DESCRIPTION
**Pull request by Delawen**
This should make some tests less flaky...

### CODE REVIEW

**Comment by gashcrumb** [comment]
I got a passing build first try with this, going to give it a couple more test runs to be sure but so far :+1:, great!

**Comment by gashcrumb** [comment]
Hmm, after that I had two failed runs one after another.  In each case I'm clearing out the ~/.m2 and cleaning the local repo.

**Comment by Delawen** [comment]
This is weird. This should prevent any action done before the step catalog is warmed up.

**Comment by gashcrumb** [comment]
> This is weird. This should prevent any action done before the step catalog is warmed up.

Yes, lemme just as a sanity check do another sequence of test runs.  These past few tests I had the IDE open and I'm concerned that could be contributing to the problem, i.e. it's rebuilding it's cache and screwing up my maven build :smile:

**Comment by gashcrumb** [comment]
Hmm, nope 2nd try:

```
[ERROR] Errors: 
[ERROR]   IntegrationsResourceTest>IntegrationsResourceTestAbstract.kameletUri:316 » IndexOutOfBounds Index 0 out of bounds for length 0
[ERROR]   IntegrationsResourceTest.kameletUri:284 » IndexOutOfBounds Index 0 out of bounds for length 0
[INFO] 
[ERROR] Tests run: 74, Failures: 18, Errors: 2, Skipped: 1
```

**Comment by Delawen** [comment]
I'll continue to investigate, but what a weird weird weird bug.

**Pull request merged**
