### PR TITLE
feature(repositories): Add filter to md repositories

### PR DESCRIPTION
**Pull request by Delawen**
Reducing startup time (we only parse with the proper parsers)

### CODE REVIEW

**Comment by apupier** [comment]
> Reducing startup time (we only parse with the proper parsers)

Do you have figures on how much time is saved?

**Comment by Delawen** [comment]
I reduced from 3 seconds to 2 seconds. Most of the time is loading camel components :/

**Comment by Delawen** [comment]
The following hot spots to check will be:

- Avoid parsing the whole yaml/json and discard attributes quickly (maybe will reduce time?)
- Check the specific parsers to see if we can speed up that. But I am not very hopeful on this one.

**Comment by Delawen** [comment]
$ date; api/target/api-1.0.0-SNAPSHOT-runner 
vie 04 nov 2022 **09:13:50** CET
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-11-04 09:13:50,542 ERROR [io.kao.bac.met.par.ClusterParseCatalog] (main) io.fabric8.kubernetes.client.DefaultKubernetesClient@19c52111
2022-11-04 09:13:50,546 WARN  [io.fab.kub.cli.int.VersionUsageUtils] (ForkJoinPool.commonPool-worker-1) The client is using resource type 'kamelets' with unstable version 'v1alpha1'
2022-11-04 09:13:50,551 INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-5) Catalog warmed up.
2022-11-04 09:13:50,555 INFO  [io.quarkus] (main) kaoto-backend 1.0.0-SNAPSHOT native (powered by Quarkus 2.12.3.Final) started in 0.295s. Listening on: http://0.0.0.0:8081
2022-11-04 09:13:50,556 INFO  [io.quarkus] (main) Profile prod activated. 
2022-11-04 09:13:50,556 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, jgit, jsch, kubernetes-client, micrometer, opentelemetry, opentelemetry-otlp-exporter, quartz, resteasy-reactive, resteasy-reactive-jackson, scheduler, smallrye-context-propagation, smallrye-openapi, vertx]
2022-11-04 **09:13:51,783** INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-1) Catalog warmed up.

**Pull request merged**
