### PR TITLE
fix: Rest verb/uri has been renamed to path

### LINKED ISSUE #854: [BUG] Rest verb/uri has been renamed to path
**Describe the bug**
https://camel.apache.org/manual/camel-3x-upgrade-guide-3_16.html#_renamed_uri_to_path

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #854

From 3.16
https://camel.apache.org/manual/camel-3x-upgrade-guide-3_16.html#_renamed_uri_to_path

### CODE REVIEW

**Comment by lordrip** [comment]
Using the step extension, doesn't include the `path` property, so probably more adaptation is required from it

image

**Review by Delawen — APPROVED** [review]

**Comment by igarashitm** [comment]
@lordrip can you upload the original YAML? (or OpenAPI spec?)

**Comment by lordrip** [comment]
@igarashitm I updated the Rest DSL Step extension to work with both properties, `path` and `uri`, this should be good now.

### Local build
image

### Current deployment
image

**Comment by lordrip** [comment]
Also, the schema now supports `routeConfiguration` and `restConfiguration` :tada: 

image

**Pull request merged**
