### PR TITLE
chore: Update Graalvm version in GitHub workflows

### LINKED ISSUE #493: Upgrade GraalVM to 22.3.1
**Is your feature request related to a problem? Please describe.**

a newer version of GraalVM is available

**Describe the solution you'd like**

use latest released version of graalVm

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #740: Upgrade to the latest Graalvm
Recently, the versioning of Graalvm was changed ( more info for GitHub workflow step is here https://github.com/graalvm/setup-graalvm#migrating-from-graalvm-223-or-earlier-to-the-new-graalvm-for-jdk-17-and-later) according to which, we need to update our workflows. 

The new versions are released under the [GraalVM Free Terms and Conditions (GFTC) license](https://www.oracle.com/downloads/licenses/graal-free-license.html) so we should carefully read it and also consider to switching from `Oracle Graalvm` to `Graalvm-community` or `Mandrel`

### PR DESCRIPTION
**Pull request by mkralik3**
https://github.com/graalvm/setup-graalvm#migrating-from-graalvm-223-or-earlier-to-the-new-graalvm-for-jdk-17-and-later

### CODE REVIEW

**Comment by Delawen** [comment]
See
https://github.com/KaotoIO/kaoto-ui/blob/main/.github/workflows/add-standalone-jar-to-release.yml#L114-L118

**Comment by mkralik3** [comment]
@Delawen 
Do we need to specify the Graalvm version explicitly? Was there any problem with the latest one? ( for the particular Java version )

**Comment by apupier** [comment]
> I think it makes sense to have a fixed version to prevent random occurring bugs due to graalvm.

agree but it seems that they are pushing to use the "graalvm" distriution based on https://github.com/graalvm/setup-graalvm#migrating-from-graalvm-223-or-earlier-to-the-new-graalvm-for-jdk-17-and-later

If I understand well, it means that it is using Oracle Graalvm JDK instead of the community edition. the license is different https://www.oracle.com/java/technologies/javase/jdk-faqs.html#GraalVM-licensing we will need to read it carefully 

> But also, at the same time, we are not looking at minor versions of java.

End-users will pick the latest version of Java on an update of their system. There are very low chance of regression for minor Java version for the not that extensive use of Java API we are using in this project.

The graalvm has an high impact for the native binary that is generated, the end-users won't be able to update it.

**Comment by mkralik3** [comment]
Yes, it looks that with new releases, they don't use graalvm versioning as before (e.g. `22.3.2`), but they use the same version as Java, e.g. `17.0.7` , https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-17.0.7 so I would say the `version` parameter in workflows will not be applicable for next Graalvm versions.
https://github.com/graalvm/setup-graalvm#options ( up to 22.3.2 )
```
X.Y.Z (e.g., 22.3.0) for a specific GraalVM release up to 22.3.2
```

====


> If I understand well, it means that it is using Oracle Graalvm JDK instead of the community edition. the license is different https://www.oracle.com/java/technologies/javase/jdk-faqs.html#GraalVM-licensing we will need to read it carefully. I think we should also ask what Quarkus is recommending and internally what Red Hat is recommending.

We can use different `distribution`, `graalvm-community` or `mandrel`. If I understand correctly, `mandrel` is primarily intended to use with Quarkus. 
https://github.com/graalvm/mandrel#mandrel
https://developers.redhat.com/blog/2021/04/14/mandrel-a-specialized-distribution-of-graalvm-for-quarkus

**Comment by mkralik3** [comment]
Unfortunately, ubuntu and windows native build constantly fail on this error
```
Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
``` 
Maybe similar? (https://github.com/oracle/graal/issues/6793)

However, it passes on macOS which has more powerful hardware ( +1CPU core, +7GB ram ) 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
which can be a root cause because on macOS, the peek for memory in the log shows more then 7GB of ram. ( which is in ubuntu/windows)
```
 88.5s (10.4% of total time) in 254 GCs | Peak RSS: 7.25GB | CPU load: 2.72
 ```

**Comment by mkralik3** [comment]
I found a workaround. By `quarkus.native.native-image-xmx`, we can instruct GraalVM to use 5GB of maximum heap
 https://quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus.native.native-image-xmx

**Comment by mkralik3** [comment]
>  I think it makes sense to have a fixed version to prevent random occurring bugs due to graalvm.

If I understand this https://github.com/graalvm/setup-graalvm/issues/47/#issuecomment-1596650126 correctly, we can specify a full version, e.g. `17.0.7`, and the new version should not break anything since it will have a different full version of java.

Also `Madrel` is not supported on macOS https://github.com/graalvm/mandrel/issues/114, so I have switched to `graalvm-community`

**Review by Delawen — APPROVED** [review]

**Comment by Delawen** [comment]
We need the companion PR for https://github.com/KaotoIO/kaoto-ui/blob/main/.github/workflows/add-standalone-jar-to-release.yml#L114-L118

**Comment by mkralik3** [comment]
@Delawen sure, I have created a PR: https://github.com/KaotoIO/kaoto-ui/pull/2118

**Pull request merged**
