### PR TITLE
fix: Close log stream on request completion

### PR DESCRIPTION
**Pull request by astefanutti**
Currently the log stream is closed when the `streamlogs` method returns, which results the generator to always fails, as it  reads from it asynchronously:

```
2023-03-08 09:28:33,844 ERROR [io.kao.bac.dep.ClusterService] (executor-thread-5) Can't get more information from log: java.io.IOException: Stream closed`
``` 

This PR delays the closing of the log stream until the request completes, either because the connection is closed client side, e.g. the browser page that issued the request has been closed, or because the watch request to the downstream Kubernetes cluster has completed.

In the later case, it's not entirely clear how the Fabric8 `Kubernetes-client` reports HTTP code returned by the watch request. It seems it always returns 200, even if an error occurred, like when the pod is deleted, for which case a JSON object containing the HTTP code is returned as part of the request body, interleaved with plain logs. It would be useful to propagate those errors up to the client. So one option would be to parse that last message, but that would complexity the logic a lot. Or reach out to the Fabric8 `Kubernetes-client` team.

### CODE REVIEW

**Comment by astefanutti** [comment]
@Delawen I've tested this PR with the frontend deployed locally and haven't faced KaotoIO/kaoto-ui#757. Are there any special conditions to reproduce it?

**Comment by Delawen** [comment]
No idea, it always happens to me.

**Comment by astefanutti** [comment]
Out of curiosity, what Web browser do you use?

**Comment by Delawen** [comment]
image

**Review by Delawen — APPROVED** [review]

**Comment by astefanutti** [comment]
`TextDecoderStream` API is supported since Firefox 105+, so that seems to confirm it: 

https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream#browser_compatibility

If you have the option to upgrade, that should fix the issue, otherwise we may want to polyfill it in the UI.

**Pull request merged**
