### PR TITLE
fix: Make sure we use the proper class

### LINKED ISSUE #583: [BUG] `SyntaxError: Expected ',' or '}' after property value` when string field has a integer-like source
**Describe the bug**

**To Reproduce**
1. Go to source code editor
2. Paste
```
- from:
    uri: slack:test
    parameters:
      maxResults: 1
    steps: []
```
3. Click `Sync code`
4. --> nothing happens in Canvas
5. 

**Expected behavior**

**Logs**
in console log:

```
SyntaxError: Expected ',' or '}' after property value in JSON at position 8351
overrideMethod @ VM510 react_devtools_backend.js:2655
```

The request which seems to be incorrect is:

```
http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/api/v1/integrations
```

with payload:
```
- from:
    uri: slack:test
    parameters:
      maxResults: 1
    steps: []
```

returns response like:
```
{
	"steps": [
		{
			"name": "slack",
			"type": "START",
			"id": "slack-consumer",
			"kind": "Camel-Connector",
			"icon": "data:image/svg+xml;base64,XXXXXXX\n",
			"title": "Slack",
			"description": "Send and receive messages Error processing deployment: java.lang.Integer cannot be cast to java.lang.String (through reference chain: io.kaoto.backend.api.resource.v1.model.Integration["steps"]->java.util.ImmutableCollections$ListN[0]->io.kaoto.backend.model.step.Step["parameters"]->java.util.LinkedList[8]->io.kaoto.backend.model.parameter.StringParameter["value"])
```

it is coming from example from Red Hatter Hugo Guerrero https://github.com/hguerrero/serverless-examples/blob/4233bbc1168eecdc70f2f967ba80adc67b4b070a/knative-slack-demo/camel-source/camel-slack-source.yaml#L24

### PR DESCRIPTION
**Pull request by Delawen**
Fixes #583

Waiting for #602 to be merged. After that, rebase and merge.

### CODE REVIEW

**Comment by apupier** [comment]
it is not fixing boolean converted inside data format as mentioned [here](https://github.com/KaotoIO/kaoto-backend/pull/602#issuecomment-1494007157)

**Review by apupier — CHANGES_REQUESTED** [review]
adding tests for the different use cases spotted is important, especially given that one of the point is not fixed contrarily to what was expected

**Comment by Delawen** [comment]
> it is not fixing boolean converted inside data format as mentioned https://github.com/KaotoIO/kaoto-backend/pull/602#issuecomment-1494007157

Sorry, I read the example wrong. Inside `marshal` we are not distinguishing the proper type. Let me fix it.

**Review by apupier — CHANGES_REQUESTED** [review]
Inside unmarshal, it is not working for complex objects:
```
- from:
    uri: 'timer:'
    steps:
    - unmarshal:
        xstream:
          aliases:
            - key: aKey
              value: aValue
 ```
 is replaced with:
 ```
- from:
    uri: 'timer:'
    steps:
    - unmarshal:
        xstream:
          aliases: {}
```

**Comment by Delawen** [comment]
I would say this is another bug/feature, but let's try to fix it on this PR too.

**Review by apupier — APPROVED** [review]

**Pull request merged**
